spring:
  datasource:
    url: jdbc:mysql://localhost/ads_projeto
    password: ${DB_PASSWORD} #KW3Ok9c6+bnfhMV
    username: ${DB_USERNAME} #GSO
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuração do Hibernate para criação automática de tabelas
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect